version: 2.1

jobs:
  lint-app:
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
  build-docker:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: Build docker container
          command: |
            echo "--------- The images is Building ------------"

            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed thuantd8/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user thuantd8/udagram-api-user:v1
            
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend thuantd8/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy thuantd8/udagram-reverseproxy:v1

            echo "-------- All images built succesfully ----------"

            echo " ------- Login dockerhub--------"

            docker login -u thuantd8 -p $DOCKERPASS

            echo "----------- Push all images to dockerhub-------"

            docker push thuantd8/udagram-api-feed:v1
            docker push thuantd8/udagram-api-user:v1
            docker push thuantd8/udagram-frontend:v1
            docker push thuantd8/udagram-reverseproxy:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]


